### PR TITLE
support using shared dict as a queue to store span

### PR DESCRIPTION
**Pull request by wangrzneu**
solve https://github.com/yangxikun/opentelemetry-lua/issues/5

### CODE REVIEW

**Comment by yangxikun** [comment]
@wangrzneu I found a simple way to fix the problem of lose spans when nginx is reload.
When timer's premature is true, export spans directly:

```lua
local function flush_batches(premature, self)
    if premature then
        ngx.log(ngx.ERR, "exiting, try export spans")

        if #self.queue > 0 then
            table.insert(self.batch_to_process, self.queue)
        end

        if #self.batch_to_process == 0 then
            return
        end

        process_batches(nil, self, self.batch_to_process)
        return
    end

    ......
end
```

The debug log:

```text
172.18.0.6 - - [23/May/2022:16:28:42 +0000] "GET /test/e2e HTTP/1.1" 200 9 "-" "Go-http-client/1.1"
2022/05/23 16:28:44 [error] 4208#4208: *60 [lua] batch_span_processor.lua:31: exiting, try export spans, context: ngx.timer, client: 172.18.0.6, server: 0.0.0.0:80
2022/05/23 16:28:44 [error] 4208#4208: *60 [lua] http_client.lua:50: do_request(): send status: 200, context: ngx.timer, client: 172.18.0.6, server: 0.0.0.0:80
```

But I'm not sure it's reliable right now, another way is when timer's premature is true, save spans to shared dict.

**Comment by yangxikun** [comment]
@wangrzneu I have test the ngx.timer.at on openresty/1.19.9.1, if premature is true, `batch_span_processor` can continuous exporting spans, the nginx worker doesn't exit until `batch_span_processor` finish its job.

**Comment by wangrzneu** [comment]
@yangxikun I think this method can solve this problem, but another reason to use shared dict is that I want to be able to limit memory usage, not just the count like the design https://github.com/apache/skywalking-nginx-lua.

**Comment by wangrzneu** [comment]
> @yangxikun I think this method can solve this problem, but another reason to use shared dict is that I want to be able to limit memory usage, not just the count like the design https://github.com/apache/skywalking-nginx-lua.

You may think using shared dict may be too complicated. I think the solution you propose can solve this problem, and I will implement it.
I will add a method to get the span count in the queue, and add return values to the on_end method to show whether the span is added to the queue successfully and the failure reason. This can make us know whether the queue size is enough.

**Comment by wangrzneu** [comment]
I create a new PR https://github.com/yangxikun/opentelemetry-lua/pull/8.

**Pull request closed without merging**
