### PR TITLE
Add openresty batch span processor and metrics reporter

### PR DESCRIPTION
**Pull request by plantfansam**
This PR adds a few things:

1. A batch span processor aimed at running within high-volume `openresty` deployments.[^1] This implementation ended up being different enough from the existing batch span processor that I created a new one. Happy to refactor the existing batch span processor instead, if you prefer @yangxikun. The implementation takes care to ensure that no changeable data is shared within `ngx.timer.at` invocations. Each batch export gets its own exporter and http client instance. 
1. A Lua implementation of the [OpenTelemetry's Ruby SDK's MetricsReporter](https://github.com/open-telemetry/opentelemetry-ruby/pull/510), which can be used to send metrics about the export pipeline. This is useful for monitoring. [PR#28, which I closed](https://github.com/yangxikun/opentelemetry-lua/pull/28/files) has code which instruments the `batch_span_processor` implementation, but I did not include that here. Happy to add.
1. Multiple returned values from `call_collector` within `otlp.lua`. These return statements are used for metrics reporting.
1. Adds fallback http client configuration based on `opentelemetry.global` settings.

[^1]:  The `lua-nginx-module` docs [describe data sharing within a single nginx worker](https://github.com/openresty/lua-nginx-module#data-sharing-within-an-nginx-worker): You can also share changeable data among all the concurrent requests of each Nginx worker process as long as there is no nonblocking I/O operations (including [ngx.sleep](https://github.com/openresty/lua-nginx-module#ngxsleep)) in the middle of your calculations. As long as you do not give the control back to the Nginx event loop and ngx_lua's light thread scheduler (even implicitly), there can never be any race conditions in between.

### CODE REVIEW

**Comment by yangxikun** [comment]
First thanks for the work. But I have some problem about the new implementation of batch span processor:
1. Export each batch spans will consumes one nginx timer, and the nginx timer has some limitation([lua_max_pending_timers](https://github.com/openresty/lua-nginx-module#lua_max_pending_timers) and [lua_max_running_timers](https://github.com/openresty/lua-nginx-module#lua_max_running_timers) etc): https://github.com/openresty/lua-nginx-module#ngxtimerat
2. Why we should create exporter and http client interface for each batch, is there any data race?
3. The original implemetation of batch span processor may have some "data race" about `self.batch_to_process`.
Such as some call about `process_batches_timer(self, self.batch_to_process)` and `process_batches(nil, self, self.batch_to_process)`, We can fix this data race by a temp var, just like in `flush_batches`:

```lua
    -- copy batch_to_process, avoid conflict with on_end
    local batch_to_process = self.batch_to_process
    self.batch_to_process = {}

    process_batches(nil, self, batch_to_process)
```

The `process_batches` will make net I/O, this will cause current lua light thread be suspend, and schedule another one.
The `process_batches_timer` will create a nginx timer, I'am not sure whether this will cause scheduling.

Some explanation in  [describe data sharing within a single nginx worker](https://github.com/openresty/lua-nginx-module#data-sharing-within-an-nginx-worker):
You can also share changeable data among all the concurrent requests of each Nginx worker process as long as there is no nonblocking I/O operations (including [ngx.sleep](https://github.com/openresty/lua-nginx-module#ngxsleep)) in the middle of your calculations. As long as you do not give the control back to the Nginx event loop and ngx_lua's light thread scheduler (even implicitly), there can never be any race conditions in between.

**Comment by plantfansam** [comment]
Thanks @yangxikun! In reply...

> Export each batch spans will consumes one nginx timer, and the nginx timer has some limitation([lua_max_pending_timers](https://github.com/openresty/lua-nginx-module#lua_max_pending_timers) and [lua_max_running_timers](https://github.com/openresty/lua-nginx-module#lua_max_running_timers) etc): https://github.com/openresty/lua-nginx-module#ngxtimerat

I think I understand. So the current implementation of `batch_span_processor` has the `batch_to_process` field in order to reduce number of nginx timers? I think that is a good optimization. I am curious: have you encountered issues with running out of nginx timers in production?

> Why we should create exporter and http client interface for each batch, is there any data race?

I reread the http_client code, and I do not think there is a data race currently. However, if we want multiple batches to re-use the same HTTP connection, then we would have a data race (we would need to store stateful http connection as field on otlp exporter instance). With current implementation, though, we do not need to initialize a new http_client for each exporter. `exporter.otlp` does not mutate state, so we do not need to create new copy for each export.[^1]

> The original implemetation of batch span processor may have some "data race" about self.batch_to_process.
Such as some call about process_batches_timer(self, self.batch_to_process) and process_batches(nil, self, self.batch_to_process), We can fix this data race by a temp var, just like in flush_batches:

I agree with this. I can make a PR to make that change.

I think there is another data race in `batch_span_processor.lua`, specifically with `.is_timer_running`. I don't think we can set this field on the batch span processor from a running nginx timer.

So the big question: **should I try to change existing batch_span_processor to remove all data races, or update this one**? I am fine with either choice.

[^1]: I wonder if we need to remove the ngx.sleep calls from the exporter, since sleep surrenders control to the nginx event loop. Not sure.

**Comment by plantfansam** [comment]
I tried to modify existing BSP to remove data races here https://github.com/yangxikun/opentelemetry-lua/pull/31. Could be an alternative.

**Comment by yangxikun** [comment]
1. The original BSP implement use `is_timer_running` to make sure one export spans timer in one nginx worker. This design is learned from https://github.com/apache/apisix/blob/f78d0459837c22723f6481af54b37d00932386fe/apisix/utils/batch-processor.lua
2. I have encountered out of nginx timers when stress Testing my lua module.

**Comment by yangxikun** [comment]
1. The original BSP implement use is_timer_running to make sure one export spans timer in one nginx worker. This design is learned from https://github.com/apache/apisix/blob/f78d0459837c22723f6481af54b37d00932386fe/apisix/utils/batch-processor.lua
2. I have encountered out of nginx timers when stress testing my lua module. 😓
3. I prefer to fix the data race in existing batch_span_processor.

**Comment by plantfansam** [comment]
OK, will continue conversation on https://github.com/yangxikun/opentelemetry-lua/pull/31!

**Pull request closed without merging**
