### PR TITLE
[DRAFT] Update name and interface for textmapgetter/textmapsetter

### PR DESCRIPTION
**Pull request by plantfansam**
When working on #44 (see [draft](https://github.com/plantfansam/opentelemetry-lua/pull/2/files)), I learned that `ngx.req.set_header` does not set response headers. There is also a special method for getting response headers (`ngx.resp.get_headers()`). To avoid confusion, I renamed `text_map_getter` and `text_map_setter` to `request_header_getter` and `request_header_setter`.

To maintain symmetry between `request_header_*` and `response_header_*`, I also updated the propagators to assume that `ngx` was passed to them (instead of `ngx.req`). If we do not change this assumption, then the trace context propagator and baggage propagator would accept `ngx.req` as a carrier, while the `traceresponse` propagator would accept `ngx`.

**This would be a breaking change**.  It's OK if you'd rather not change the existing propagators @yangxikun, just let me know.

### CODE REVIEW

**Comment by yangxikun** [comment]
Seems we need a new "trace context propagator" to extract `traceresponse` from upstream response header and inject `traceresponse` to downstream response. So maybe we can keep the trace context propagator and baggage propagator accept ngx.req as a carrier.

Sorry for the quickly say "sure" on #44. After checking opentelemetry specification, I found there was not spec about `traceresponse`. And `traceresponse` still in w3c trace context draft, maybe we can wait for the opentelemetry specification to include `traceresponse`.

Does your service need this feature now?

**Comment by plantfansam** [comment]
> Sorry for the quickly say "sure" on #44. After checking opentelemetry specification, I found there was not spec about `traceresponse`. And `traceresponse` still in w3c trace context draft, maybe we can wait for the opentelemetry specification to include `traceresponse`.

No problem! We do need this feature, but we can implement elsewhere if you do not want it in `opentelemetry-lua` yet!

**Comment by plantfansam** [comment]
> Seems we need a new "trace context propagator" to extract `traceresponse` from upstream response header and inject `traceresponse` to downstream response.

Yes, I have a draft of that here 😄 https://github.com/plantfansam/opentelemetry-lua/pull/2. I think it makes sense to keep carrier as `ngx.req` for the `TextMapPropagator`.

**Comment by plantfansam** [comment]
Closing this until we actually want it.

**Pull request closed without merging**
