### PR TITLE
Add 0.2-0 rockspec

### PR DESCRIPTION
**Pull request by plantfansam**
If possible, I'd love to release https://github.com/yangxikun/opentelemetry-lua/pull/12. 

I think this Rockspec includes the recent changes from https://github.com/yangxikun/opentelemetry-lua/pull/12. Let me know if we need to do anything else to prepare for a release (or if you do not want to do a release yet).

### CODE REVIEW

**Comment by yangxikun** [comment]
We can release after #14

**Comment by plantfansam** [comment]
> We can release after #14

🎉

**Comment by yangxikun** [comment]
@plantfansam https://luarocks.org/modules/yangxikun/opentelemetry-lua/0.2-0

**Comment by plantfansam** [comment]
> @plantfansam https://luarocks.org/modules/yangxikun/opentelemetry-lua/0.2-0

Thanks @yangxikun!

**Pull request merged**
