### PR TITLE
release v0.2.3

### PR DESCRIPTION
**Pull request by yangxikun**

### CODE REVIEW

**Comment by yangxikun** [comment]
@plantfansam Are we ready to release v0.2.3 ?

**Comment by plantfansam** [comment]
@yangxikun if you're ready, don't block on me. I can take a closer look later this week if you want me to 👀.

**Comment by yangxikun** [comment]
@plantfansam Ok, I wait for your review.

**Comment by plantfansam** [comment]
I'm 👍  for a release! Thanks!

**Pull request merged**
